(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/kp-button/index"],{"70aa":function(n,t,e){"use strict";e.r(t);var a=e("a147"),o=e.n(a);for(var c in a)"default"!==c&&function(n){e.d(t,n,(function(){return a[n]}))}(c);t["default"]=o.a},"7b69":function(n,t,e){"use strict";var a,o=function(){var n=this,t=n.$createElement;n._self._c},c=[];e.d(t,"b",(function(){return o})),e.d(t,"c",(function(){return c})),e.d(t,"a",(function(){return a}))},a147:function(n,t,e){"use strict";function a(n,t,e){return t in n?Object.defineProperty(n,t,{value:e,enumerable:!0,configurable:!0,writable:!0}):n[t]=e,n}Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var o=function(){Promise.all([e.e("common/vendor"),e.e("components/kp-icon/index")]).then(function(){return resolve(e("330f"))}.bind(null,e)).catch(e.oe)},c="k-btn",u={name:"KpButton",components:{KpIcon:o},props:{type:{validator:function(n){return["default","primary","dashed","text","info","success","warning","error"].includes(n)},default:"default"},shape:{validator:function(n){return["square","circle","circle-outline"].includes(n)},default:"square"},size:{validator:function(n){return["small","large","default"].includes(n)},default:"default"},disabled:Boolean,icon:{type:String,default:""},iconSize:{type:[Number,String],default:28},long:{type:Boolean,default:!1},plain:{type:Boolean,default:!1}},data:function(){return{prefixCls:c}},computed:{classes:function(){var n;return["".concat(c),"".concat(c,"-").concat(this.type),"".concat(c,"-").concat(this.shape),"".concat(c,"-").concat(this.size),(n={},a(n,"".concat(c,"-long"),this.long),a(n,"".concat(c,"-plain"),this.plain),n)]}},methods:{handleButtonClick:function(n){this.$emit("on-click",n)}},mounted:function(){}};t.default=u},bcc9:function(n,t,e){"use strict";e.r(t);var a=e("7b69"),o=e("70aa");for(var c in o)"default"!==c&&function(n){e.d(t,n,(function(){return o[n]}))}(c);e("05dd");var u,i=e("f0c5"),r=Object(i["a"])(o["default"],a["b"],a["c"],!1,null,"0a140087",null,!1,a["a"],u);t["default"]=r.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/kp-button/index-create-component',
    {
        'components/kp-button/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("bcc9"))
        })
    },
    [['components/kp-button/index-create-component']]
]);
